[2025-06-29T14:49:39.058+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2024-08-19T00:00:00+00:00 [queued]>
[2025-06-29T14:49:39.201+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2024-08-19T00:00:00+00:00 [queued]>
[2025-06-29T14:49:39.201+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-06-29T14:49:40.011+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-08-19 00:00:00+00:00
[2025-06-29T14:49:40.132+0000] {standard_task_runner.py:57} INFO - Started process 2397 to run task
[2025-06-29T14:49:40.210+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'scheduled__2024-08-19T00:00:00+00:00', '--job-id', '3408', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp13imi1ad']
[2025-06-29T14:49:40.300+0000] {standard_task_runner.py:85} INFO - Job 3408: Subtask insert_into_table
[2025-06-29T14:49:41.737+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2024-08-19T00:00:00+00:00 [running]> on host f561bfe7dd3a
[2025-06-29T14:49:43.381+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-08-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-19T00:00:00+00:00'
[2025-06-29T14:49:43.394+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-08-19', 'dag_with_postgres_operator_v03')
        
[2025-06-29T14:49:43.667+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T14:49:43.917+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T14:49:43.997+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-08-19', 'dag_with_postgres_operator_v03')
        , parameters: None
[2025-06-29T14:49:44.081+0000] {sql.py:427} INFO - Rows affected: 1
[2025-06-29T14:49:44.262+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=insert_into_table, execution_date=20240819T000000, start_date=20250629T144939, end_date=20250629T144944
[2025-06-29T14:49:45.988+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-29T14:49:46.178+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
