[2025-06-29T14:55:49.154+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2025-02-12T00:00:00+00:00 [queued]>
[2025-06-29T14:55:49.260+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2025-02-12T00:00:00+00:00 [queued]>
[2025-06-29T14:55:49.263+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-06-29T14:55:49.953+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2025-02-12 00:00:00+00:00
[2025-06-29T14:55:50.336+0000] {standard_task_runner.py:57} INFO - Started process 3786 to run task
[2025-06-29T14:55:50.488+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'delete_data_from_table', 'scheduled__2025-02-12T00:00:00+00:00', '--job-id', '3926', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmputx5d8y9']
[2025-06-29T14:55:50.565+0000] {standard_task_runner.py:85} INFO - Job 3926: Subtask delete_data_from_table
[2025-06-29T14:55:51.860+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2025-02-12T00:00:00+00:00 [running]> on host f561bfe7dd3a
[2025-06-29T14:55:52.820+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-12T00:00:00+00:00'
[2025-06-29T14:55:52.821+0000] {sql.py:274} INFO - Executing: 
            delete from dag_runs where dt = '2025-02-12' and dag_id = 'dag_with_postgres_operator_v03';
        
[2025-06-29T14:55:52.876+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T14:55:52.934+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T14:55:52.978+0000] {sql.py:418} INFO - Running statement: 
            delete from dag_runs where dt = '2025-02-12' and dag_id = 'dag_with_postgres_operator_v03';
        , parameters: None
[2025-06-29T14:55:52.993+0000] {sql.py:427} INFO - Rows affected: 0
[2025-06-29T14:55:53.083+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=delete_data_from_table, execution_date=20250212T000000, start_date=20250629T145549, end_date=20250629T145553
[2025-06-29T14:55:53.333+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-29T14:55:53.517+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
