[2025-06-29T12:13:46.565+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2023-03-23T00:00:00+00:00 [queued]>
[2025-06-29T12:13:46.798+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2023-03-23T00:00:00+00:00 [queued]>
[2025-06-29T12:13:46.811+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-06-29T12:13:48.324+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-03-23 00:00:00+00:00
[2025-06-29T12:13:48.613+0000] {standard_task_runner.py:57} INFO - Started process 7549 to run task
[2025-06-29T12:13:48.813+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'scheduled__2023-03-23T00:00:00+00:00', '--job-id', '1834', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpp3gq2ibg']
[2025-06-29T12:13:48.946+0000] {standard_task_runner.py:85} INFO - Job 1834: Subtask insert_into_table
[2025-06-29T12:13:50.489+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2023-03-23T00:00:00+00:00 [running]> on host f561bfe7dd3a
[2025-06-29T12:13:51.123+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2023-03-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-23T00:00:00+00:00'
[2025-06-29T12:13:51.126+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2023-03-23', 'dag_with_postgres_operator_v03')
        
[2025-06-29T12:13:51.152+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T12:13:51.212+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T12:13:51.286+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2023-03-23', 'dag_with_postgres_operator_v03')
        , parameters: None
[2025-06-29T12:13:51.288+0000] {sql.py:427} INFO - Rows affected: 1
[2025-06-29T12:13:51.368+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=insert_into_table, execution_date=20230323T000000, start_date=20250629T121346, end_date=20250629T121351
[2025-06-29T12:13:51.859+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-29T12:13:52.319+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
