[2025-06-29T14:54:09.550+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2025-06-29T14:54:09.592+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2025-06-29T14:54:09.593+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-06-29T14:54:09.810+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2024-12-28 00:00:00+00:00
[2025-06-29T14:54:09.906+0000] {standard_task_runner.py:57} INFO - Started process 3414 to run task
[2025-06-29T14:54:09.949+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'delete_data_from_table', 'scheduled__2024-12-28T00:00:00+00:00', '--job-id', '3788', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp90ur30xs']
[2025-06-29T14:54:09.997+0000] {standard_task_runner.py:85} INFO - Job 3788: Subtask delete_data_from_table
[2025-06-29T14:54:10.625+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2024-12-28T00:00:00+00:00 [running]> on host f561bfe7dd3a
[2025-06-29T14:54:11.350+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-28T00:00:00+00:00'
[2025-06-29T14:54:11.364+0000] {sql.py:274} INFO - Executing: 
            delete from dag_runs where dt = '2024-12-28' and dag_id = 'dag_with_postgres_operator_v03';
        
[2025-06-29T14:54:11.475+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T14:54:11.587+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T14:54:11.730+0000] {sql.py:418} INFO - Running statement: 
            delete from dag_runs where dt = '2024-12-28' and dag_id = 'dag_with_postgres_operator_v03';
        , parameters: None
[2025-06-29T14:54:11.732+0000] {sql.py:427} INFO - Rows affected: 0
[2025-06-29T14:54:11.832+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=delete_data_from_table, execution_date=20241228T000000, start_date=20250629T145409, end_date=20250629T145411
[2025-06-29T14:54:12.173+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-29T14:54:13.580+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
