[2025-06-29T14:49:31.936+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2024-08-19T00:00:00+00:00 [queued]>
[2025-06-29T14:49:32.005+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2024-08-19T00:00:00+00:00 [queued]>
[2025-06-29T14:49:32.006+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-06-29T14:49:32.668+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2024-08-19 00:00:00+00:00
[2025-06-29T14:49:32.755+0000] {standard_task_runner.py:57} INFO - Started process 2365 to run task
[2025-06-29T14:49:32.778+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'delete_data_from_table', 'scheduled__2024-08-19T00:00:00+00:00', '--job-id', '3396', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmphnhbti8o']
[2025-06-29T14:49:32.790+0000] {standard_task_runner.py:85} INFO - Job 3396: Subtask delete_data_from_table
[2025-06-29T14:49:33.287+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2024-08-19T00:00:00+00:00 [running]> on host f561bfe7dd3a
[2025-06-29T14:49:33.976+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2024-08-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-19T00:00:00+00:00'
[2025-06-29T14:49:33.979+0000] {sql.py:274} INFO - Executing: 
            delete from dag_runs where dt = '2024-08-19' and dag_id = 'dag_with_postgres_operator_v03';
        
[2025-06-29T14:49:34.102+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T14:49:34.195+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T14:49:34.257+0000] {sql.py:418} INFO - Running statement: 
            delete from dag_runs where dt = '2024-08-19' and dag_id = 'dag_with_postgres_operator_v03';
        , parameters: None
[2025-06-29T14:49:34.268+0000] {sql.py:427} INFO - Rows affected: 0
[2025-06-29T14:49:34.386+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=delete_data_from_table, execution_date=20240819T000000, start_date=20250629T144931, end_date=20250629T144934
[2025-06-29T14:49:34.736+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-29T14:49:35.813+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
