[2025-06-29T15:01:20.705+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2025-06-28T00:00:00+00:00 [queued]>
[2025-06-29T15:01:20.839+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2025-06-28T00:00:00+00:00 [queued]>
[2025-06-29T15:01:20.842+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-06-29T15:01:21.413+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2025-06-28 00:00:00+00:00
[2025-06-29T15:01:21.479+0000] {standard_task_runner.py:57} INFO - Started process 4895 to run task
[2025-06-29T15:01:21.516+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'delete_data_from_table', 'scheduled__2025-06-28T00:00:00+00:00', '--job-id', '4331', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpftpyzlzp']
[2025-06-29T15:01:21.573+0000] {standard_task_runner.py:85} INFO - Job 4331: Subtask delete_data_from_table
[2025-06-29T15:01:21.921+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2025-06-28T00:00:00+00:00 [running]> on host f561bfe7dd3a
[2025-06-29T15:01:22.392+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2025-06-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-28T00:00:00+00:00'
[2025-06-29T15:01:22.397+0000] {sql.py:274} INFO - Executing: 
            delete from dag_runs where dt = '2025-06-28' and dag_id = 'dag_with_postgres_operator_v03';
        
[2025-06-29T15:01:22.441+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T15:01:22.474+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T15:01:22.503+0000] {sql.py:418} INFO - Running statement: 
            delete from dag_runs where dt = '2025-06-28' and dag_id = 'dag_with_postgres_operator_v03';
        , parameters: None
[2025-06-29T15:01:22.505+0000] {sql.py:427} INFO - Rows affected: 0
[2025-06-29T15:01:22.527+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=delete_data_from_table, execution_date=20250628T000000, start_date=20250629T150120, end_date=20250629T150122
[2025-06-29T15:01:22.601+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-29T15:01:22.767+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
