[2025-06-29T15:00:12.149+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2025-05-25T00:00:00+00:00 [queued]>
[2025-06-29T15:00:12.166+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2025-05-25T00:00:00+00:00 [queued]>
[2025-06-29T15:00:12.167+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-06-29T15:00:12.221+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2025-05-25 00:00:00+00:00
[2025-06-29T15:00:12.255+0000] {standard_task_runner.py:57} INFO - Started process 4651 to run task
[2025-06-29T15:00:12.280+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'scheduled__2025-05-25T00:00:00+00:00', '--job-id', '4240', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpzgrgq6ec']
[2025-06-29T15:00:12.294+0000] {standard_task_runner.py:85} INFO - Job 4240: Subtask insert_into_table
[2025-06-29T15:00:12.450+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2025-05-25T00:00:00+00:00 [running]> on host f561bfe7dd3a
[2025-06-29T15:00:12.835+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2025-05-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-25T00:00:00+00:00'
[2025-06-29T15:00:12.846+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2025-05-25', 'dag_with_postgres_operator_v03')
        
[2025-06-29T15:00:12.939+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T15:00:13.087+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T15:00:13.097+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2025-05-25', 'dag_with_postgres_operator_v03')
        , parameters: None
[2025-06-29T15:00:13.099+0000] {sql.py:427} INFO - Rows affected: 1
[2025-06-29T15:00:13.128+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=insert_into_table, execution_date=20250525T000000, start_date=20250629T150012, end_date=20250629T150013
[2025-06-29T15:00:13.217+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-29T15:00:13.281+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
