[2025-06-29T15:17:16.770+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-29T15:17:17.653+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v01.get_sklearn scheduled__2022-05-16T00:00:00+00:00 [queued]>
[2025-06-29T15:17:17.762+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v01.get_sklearn scheduled__2022-05-16T00:00:00+00:00 [queued]>
[2025-06-29T15:17:17.762+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-06-29T15:17:18.188+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_sklearn> on 2022-05-16 00:00:00+00:00
[2025-06-29T15:17:18.822+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v01', 'get_sklearn', 'scheduled__2022-05-16T00:00:00+00:00', '--job-id', '4554', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpux8lqd28']
[2025-06-29T15:17:18.910+0000] {standard_task_runner.py:91} INFO - Job 4554: Subtask get_sklearn
[2025-06-29T15:17:18.961+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=208) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-29T15:17:19.020+0000] {standard_task_runner.py:63} INFO - Started process 218 to run task
[2025-06-29T15:17:20.392+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_python_dependencies_v01.get_sklearn scheduled__2022-05-16T00:00:00+00:00 [running]> on host 895c9b4bc327
[2025-06-29T15:17:21.920+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shivanshu' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v01' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2022-05-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-05-16T00:00:00+00:00'
[2025-06-29T15:17:21.921+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-29T15:18:00.964+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2025-06-29T15:18:01.746+0000] {process_utils.py:132} INFO - Sending 15 to group 218. PIDs of all processes in the group: [218]
[2025-06-29T15:18:01.751+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 218
[2025-06-29T15:18:01.848+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-29T15:18:01.889+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-29T15:18:02.566+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 15, in get_sklearn
    import sklearn
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 19, in <module>
    from .utils._metadata_requests import _MetadataRequester, _routing_enabled
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/__init__.py", line 9, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 21, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 20, in <module>
    from .fixes import parse_version
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/fixes.py", line 15, in <module>
    import scipy.sparse.linalg
  File "/home/airflow/.local/lib/python3.12/site-packages/scipy/sparse/linalg/__init__.py", line 131, in <module>
    from ._isolve import *
  File "/home/airflow/.local/lib/python3.12/site-packages/scipy/sparse/linalg/_isolve/__init__.py", line 4, in <module>
    from .iterative import *
  File "/home/airflow/.local/lib/python3.12/site-packages/scipy/sparse/linalg/_isolve/iterative.py", line 3, in <module>
    from scipy.sparse.linalg._interface import LinearOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/scipy/sparse/linalg/_interface.py", line 719, in <module>
    class _ProductLinearOperator(LinearOperator):
  File "/home/airflow/.local/lib/python3.12/site-packages/scipy/sparse/linalg/_interface.py", line 719, in _ProductLinearOperator
    class _ProductLinearOperator(LinearOperator):
    
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-06-29T15:18:03.191+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies_v01, task_id=get_sklearn, execution_date=20220516T000000, start_date=20250629T151717, end_date=20250629T151803
[2025-06-29T15:18:04.498+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=218, status='terminated', exitcode=2, started='15:17:18') (218) terminated with exit code 2
[2025-06-29T15:18:04.559+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
[2025-06-29T15:18:05.956+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-29T15:18:06.552+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
