[2025-06-29T14:44:03.919+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2025-06-29T14:44:04.164+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2025-06-29T14:44:04.165+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-06-29T14:44:04.482+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-04-01 00:00:00+00:00
[2025-06-29T14:44:04.640+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'scheduled__2024-04-01T00:00:00+00:00', '--job-id', '2981', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpsyn_tx6k']
[2025-06-29T14:44:04.647+0000] {standard_task_runner.py:85} INFO - Job 2981: Subtask insert_into_table
[2025-06-29T14:44:04.628+0000] {standard_task_runner.py:57} INFO - Started process 1235 to run task
[2025-06-29T14:44:04.851+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2024-04-01T00:00:00+00:00 [running]> on host f561bfe7dd3a
[2025-06-29T14:44:05.607+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T00:00:00+00:00'
[2025-06-29T14:44:05.634+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-04-01', 'dag_with_postgres_operator_v03')
        
[2025-06-29T14:44:05.720+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T14:44:05.912+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T14:44:05.985+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-04-01', 'dag_with_postgres_operator_v03')
        , parameters: None
[2025-06-29T14:44:06.002+0000] {sql.py:427} INFO - Rows affected: 1
[2025-06-29T14:44:06.140+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=insert_into_table, execution_date=20240401T000000, start_date=20250629T144403, end_date=20250629T144406
[2025-06-29T14:44:07.147+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-29T14:44:07.456+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
