[2025-06-29T12:16:48.405+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2023-05-29T00:00:00+00:00 [queued]>
[2025-06-29T12:16:48.482+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2023-05-29T00:00:00+00:00 [queued]>
[2025-06-29T12:16:48.483+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-06-29T12:16:48.779+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-05-29 00:00:00+00:00
[2025-06-29T12:16:48.839+0000] {standard_task_runner.py:57} INFO - Started process 8127 to run task
[2025-06-29T12:16:48.887+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'scheduled__2023-05-29T00:00:00+00:00', '--job-id', '2040', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp1ktz8kzn']
[2025-06-29T12:16:48.905+0000] {standard_task_runner.py:85} INFO - Job 2040: Subtask insert_into_table
[2025-06-29T12:16:49.564+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2023-05-29T00:00:00+00:00 [running]> on host f561bfe7dd3a
[2025-06-29T12:16:50.289+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2023-05-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-29T00:00:00+00:00'
[2025-06-29T12:16:50.290+0000] {sql.py:274} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2023-05-29', 'dag_with_postgres_operator_v03')
        
[2025-06-29T12:16:50.440+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T12:16:50.540+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-29T12:16:50.602+0000] {sql.py:418} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2023-05-29', 'dag_with_postgres_operator_v03')
        , parameters: None
[2025-06-29T12:16:50.604+0000] {sql.py:427} INFO - Rows affected: 1
[2025-06-29T12:16:50.667+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=insert_into_table, execution_date=20230529T000000, start_date=20250629T121648, end_date=20250629T121650
[2025-06-29T12:16:50.858+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-29T12:16:51.108+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
